### PR TITLE
Property sheets simplification

### PR DESCRIPTION
**Pull request by JunielKatarn**
I made a similar refactoring for Project64.

In short, it removes redundant MSBuild settings and centralizes them in the appropriate platform, configuration, or common property sheet.

The change seems a little large, but it's easy to test by just building (i.e. `MSBuild AziAudio.sln /p:Platform=x64 /p:Configuration=Release`).

### CODE REVIEW

**Comment by JunielKatarn** [comment]
Hi @Azimer.
i added this change to make VCXPROJ settings more modular and easier to manage.
Test-built all permutations (Win32, x64) x (Debug, Release).

**Comment by Azimer** [comment]
Sorry for the lack of traction on this.  It's been a rough last 6-9 months.  I'll spare you the details and issue a merge.  We can always revert or fix issues later.  Thanks!

**Comment by JunielKatarn** [comment]
@Azimer No sweat. It's understandable. These changes are part of an effort to set up a buildbot for this plugin. I already have a couple more PRs to get this done.

On that note, is there an email address or some other method I can chat with you?

**Comment by Azimer** [comment]
I've got Yahoo mail with the same alias.

**Pull request merged**
