### PR TITLE
New Audiocode

### PR DESCRIPTION
**Pull request by Azimer**
Work in progress new Audiocode

### CODE REVIEW

**Comment by AmbientMalice** [comment]
WDC sounds great.

**Comment by oddMLan** [comment]
There's some pretty noticeable audio popping/cracking... dunno what to call it. On Conker's Bad Fur Day. With whichever backend the project uses as default when compiling it. Settings in the Audio have little effect, no matter LLE or HLE. Fixed Audio Timing enabled, Sync Using Audio disabled.

**Comment by Frank-74** [comment]
@oddMLan And TWINE is very bad with new audiocode.

To build with a different backend, change this line:
https://github.com/Azimer/AziAudio/blob/master/AziAudio/main.cpp#L116

Options are:
SND_DRIVER_DS8L
SND_DRIVER_DS8
SND_DRIVER_XA2L
SND_DRIVER_XA2
SND_DRIVER_NOSOUND

The L is legacy, old audiocode.  TWINE sounds good with XA2L, bad with XA2.

**Comment by Azimer** [comment]
Thanks for the feedback. Next commit well have XA2L as default until I can "burn in" the new audio code for me. RE2, Gauntlet Legends and Tarzan are my goto MusyX tests. Obviously I missed something along with CBFD.

**Comment by AmbientMalice** [comment]
You should probably be wary of PJ64's audio code, too. If there's something wrong on PJ64's end, it could send you on wild goose chases.

**Pull request merged**
