### PR TITLE
Added Unix shell script for building outside Windows.

### PR DESCRIPTION
**Pull request by cxd4**
This new file I've created, `make.sh`, will compile the plugin either on Unix or Linux-based platforms or also on Windows, if you run the script through Git Bash/MSYS terminal to emulate the Unix command shell on Windows.  (If you do this, it compiles on Windows using MinGW, or I suppose Cygwin in theory.  The primary point however is to have a Linux build script.)

In the process, I've attempted simplifications of several build files we had formerly in the repo root.
See issue https://github.com/Azimer/AziAudio/issues/129 for more discussion.

### CODE REVIEW

**Comment by weinerschnitzel** [comment]
Next step is to move the solution files to the Build directory?

**Comment by cxd4** [comment]
Um, potentially, though I am happy to leave that to other contributors.

I'm no good at the MSVC project syntax/solution files and would need to have Xbox dev skills to move your Xbox solution into the build folder without fear of breaking anything.

I assumed people might prefer leaving the VC2013 solution as-is in the root directory since that's the official build method Azimer and most use.

**Comment by weinerschnitzel** [comment]
Organization tells me to put them all in Build, or just leave them together. Of course, if Azimer just wants the vs2013 solution at root, that's fine as well. I'll keep the Xbox solution building like I promised, I just want to be on the same page of understanding if we are moving these solutions or not.

Frankly I'm also happy leaving them where they are. :) Whatever's clever.

**Comment by cxd4** [comment]
My personal preference would be to see the Xbox solution moved under the "Build" folder.

I, individually, would not exactly mind if the same were done with VC2008 and VC2013 files as well, but I prefer to leave that for Azimer to decide.  Part of the issue could be how zilmar has the property sheets integrating with his 2008 solution and the shared folder with 2013.

Technically, since it is Azimer's repository and not my repository, my view is that my opinions can be moved to the "Build" subfolder and Azimer's opinions can be kept to the root folder.  Sure, if this was my repo I may have done it the other way around (e.g., my opinion is that `make.sh` is the most important build file), but all I was really concerned with was just cleaning up the root organization.  I understand that it's a little inconsistent to only move most, but not all, of the build files to the same folder, but I think that in exchange it's cleaner than it was before.

**Pull request merged**
