### PR TITLE
Got the plugin to build on Linux without any warnings.

### PR DESCRIPTION
**Pull request by cxd4**
I'm sure that at least a couple things I did here will raise some eyebrows, so feel free to ask.

First, I'd like to say that I've noticed most people usually go by the "Files changed" tab on GitHub website, to view the overall changes in one single diff.  That's why I stopped making multiple commits in one single pull request.  In this case I would personally prefer to read all the individual commits rather than one gigantic, merged diff.  Only reason this PR isn't split into multiple PRs is because I stood up to 2 AM finishing this on my seldom-working Linux laptop with seldom-working, crappy Internet.

One thing that does work!  The 64-bit Linux port of this plugin, as tested in Mupen64 64-bit 1.5.
(It says "Azimer's DS8" in the plugin selection list, but that can be tended to later.)

Here's what this pull request doesn't address:
* Adding my Unix shell script to the repository, as there are plenty of build scripts in this repository already, and I would rather wait until any other matters remaining would be addressed.
* Sound playback, as we have no sound device available but the "No Sound" device.
* Potential run-time collisions with global variable names linked under parent executables.
* I doubt that the No Sound driver works as fully under Linux as it does on Windows.
* I have yet to test on 32-bit Mupen64 0.5.
* AT&T vs. Intel x86 assembler syntax errors if compiling with `-masm=intel` ... so I currently have it at the default AT&T asm output which the C compiles to.

### CODE REVIEW

**Comment by Azimer** [comment]
Looks good.  Writing in here to let you know I've seen it but have to review it yet.  Thanks!

**Comment by cxd4** [comment]
Glad to hear this can work and thanks for letting me know.

I also can divide this PR into sub-PRs at this point if you prefer, since I have the whole list of changes laid out for me already in this PR that I could reference.  I just wasn't able to strategically allocate every change to its own PR when I first started this port because my crappy laptop puts a rush on everything (except waiting 15 minutes for search engines to finish loading the page to answer my questions).

**Comment by Azimer** [comment]
Sorry for the very long delay merging this.  I have been stupid busy lately working on a huge database build for work.

**Comment by cxd4** [comment]
I should apologize really for not splitting it into smaller PRs (that would have been best for testing).
Kept meaning to just kept slacking.

I hope that you will soon get the bubble of time you will need to resume play with these projects.

**Pull request merged**
